export const MAX_LOG_FILE_SIZE_BYTES = 50 * 1024 * 1024;

export const FILE_INGESTION_ERROR_CODE = {
  FILE_SIZE_EXCEEDED: "FILE_SIZE_EXCEEDED",
  BINARY_PAYLOAD_REJECTED: "BINARY_PAYLOAD_REJECTED",
  FILE_READ_FAILED: "FILE_READ_FAILED",
} as const;

export type FileIngestionErrorCode =
  (typeof FILE_INGESTION_ERROR_CODE)[keyof typeof FILE_INGESTION_ERROR_CODE];
